    SCREEN_WIDTH equ 320
    SCREEN_HEIGHT equ 200
    VIDEO_BUFFER_SIZE equ SCREEN_WIDTH * SCREEN_HEIGHT

    MAX_COLOR equ 0x3F
    CENTER_OFFSET equ 0x7DA0
    BUFFER_SIZE equ 0x10000

    %ifdef DOS
    VIDEO_MODE_13H equ 0x13
    TEXT_MODE_3H equ 0x03
    BIOS_VIDEO_INTERRUPT equ 0x10
    VIDEO_MEMORY_SEGMENT equ 0xA000
    PALETTE_INDEX_PORT equ 0x03C8
    PALETTE_DATA_PORT equ 0x03C9

    VGA_INPUT_STATUS_REGISTER equ 0x3DA
    VERTICAL_RETRACE_STATUS_BIT equ 0x08

    KEYBOARD_DATA_PORT equ 0x60

    %endif
